# Generated by Django 2.1 on 2018-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_errorcode_manufacturer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatingmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='id',
        ),
        migrations.AlterField(
            model_name='heatingmodel',
            name='model_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
